# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fastapi
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: fastapi-port
  selector:
    app: {{ .Release.Name }}-fastapi