# values.yaml
annotations:
  prometheus.io/scrape: "true"

updateStrategy: {}
#  rollingUpdate:
#    maxUnavailable: 1
#  type: RollingUpdate

tolerations: {}
  # - key: fastapi-test
  #   operator: Equal
  #   value: gateway
  #   effect: NoSchedule

affinity: {}
# # An example of preferred pod anti-affinity, weight is in the range 1-100
# podAntiAffinity:
#   preferredDuringSchedulingIgnoredDuringExecution:
#   - weight: 100
#     podAffinityTerm:
#       labelSelector:
#         matchExpressions:
#         - key: app.kubernetes.io/name
#           operator: In
#           values:
#           - ingress-nginx
#         - key: app.kubernetes.io/instance
#           operator: In
#           values:
#           - ingress-nginx
#         - key: app.kubernetes.io/component
#           operator: In
#           values:
#           - controller
#       topologyKey: kubernetes.io/hostname

# # An example of required pod anti-affinity
# podAntiAffinity:
#   requiredDuringSchedulingIgnoredDuringExecution:
#   - labelSelector:
#       matchExpressions:
#       - key: app.kubernetes.io/name
#         operator: In
#         values:
#         - ingress-nginx
#       - key: app.kubernetes.io/instance
#         operator: In
#         values:
#         - ingress-nginx
#       - key: app.kubernetes.io/component
#         operator: In
#         values:
#         - controller
#     topologyKey: "kubernetes.io/hostname"

nodeSelector: {}
  # kubernetes.io/os: linux

replicaCount: 1

resources: {}
  # limits:
  #   cpu: "200m"
  #   memory: "256Mi"
  # requests:
  #   cpu: "100m"
  #   memory: "128Mi"

image:
  repository: penghian.azurecr.io/fastapi-test
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 3000

fastapi:
  db_url: |-
    a
  key: |-
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
