# prometheus-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  prometheus.yml: |
    global:
      scrape_interval:     {{ .Values.scrapeInterval }}
      evaluation_interval: {{ .Values.evaluationInterval }}

    scrape_configs:
    # Dynamic service discovery configuration
    - job_name: 'kubernetes-stakefish-metrics'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: 'true'
