# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fastapi
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fastapi
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fastapi
    spec:
      containers:
      - name: my-fastapi-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/usr/local/bin/uvicorn"]
        args:
          - "main:app"
          - "--host"
          - "0.0.0.0"
          - "--port"
          - "{{ .Values.service.port }}"
          - "--reload"
        env:
          - name: DATABASE_URL
            value: "{{ .Values.db_url }}"
        ports:
        - name: fastapi-port
          containerPort: {{ .Values.service.port }}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - name: azure-ca-pem-volume
          mountPath: /etc/ssl/certs/azure_ca.pem
          subPath: azure_ca.pem
          readOnly: true
      volumes:
      - name: azure-ca-pem-volume
        secret:
          secretName: azure-ca-pem
